name: Run Tests
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --upgrade --upgrade-strategy eager
          pip install -r dev-requirements.txt --upgrade --upgrade-strategy eager

      - name: Format and lint
        run: |
          black . --check
          flake8 .
          isort . --check-only --diff

      - name: Run tests suite
        run: |
          pytest .
